### ISSUE TITLE
Avoid using the height and width attributes on html tags

### ISSUE THREAD

**Issue by alexander-dubinski** [DVDaniels/Tea_Cozy_Project#1]
https://github.com/DVDaniels/Tea_Cozy_Project/blob/d35567b89bd7fd5055b421e26a4f551d24cdb5ea/index.html#L43

As a general rule of thumb and best practice, using the height and width attributes to control the style of HTML is old school and doing this with CSS is preferred. This is because in general all styles are in the CSS so putting the height and width outside the CSS makes the code more difficult to debug and understand. Furthermore you cannot use percentages and ems on HTML attributes.

**Comment by DVDaniels** [comment]
Removed height and width from HTML.
