### ISSUE TITLE
Use a proper copyright symbol

### ISSUE THREAD

**Issue by alexander-dubinski** [DVDaniels/Tea_Cozy_Project#2]
https://github.com/DVDaniels/Tea_Cozy_Project/blob/d35567b89bd7fd5055b421e26a4f551d24cdb5ea/index.html#L107

Unless not possible for some reason, a copyright symbol should be used instead or writing the word "copyright"

This can be done by adding the HTML unicode character in your HTML, like below:
```
&copy;
```

**Comment by DVDaniels** [comment]
I corrected the copyright issue.
