### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by alexander-dubinski** [DVDaniels/Tea_Cozy_Project#3]
### Criteria 1: HTML Structure  
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Structure of the HTML generally follows best practices and is well formatted.
 
### Criteria 2: Visual Layout
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Visual layout looks good but does not scale well with different screen sizes
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ Flew box is implemented but fails when the screen becomes larger due to overriding CSS and HTML attributes (more on this below)
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 2 (Approaches Expectations)
* _Comment(s):_ When the user's screen is a specific size everything looks great and is in spec but go beyond that, and the document is not in spec. Two most prominent of example where the document is out of spec is that there is a large gap between the top of the screen and the header, and the content is not centered for larger screens. The gap on the is present for all screen sizes.
 
### Overall Score: 12/16
This project is overall well done but Fails to meet spec in many areas outlined above. Fix these issues and the project will be near perfect! Keep it up and happy coding!

**Comment by DVDaniels** [comment]
I am still having problems with flex. Could use some hints on this one.
